# Generated by Django 3.1 on 2020-08-27 02:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200817_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cuisine_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=None, null=True, size=None),
        ),
    ]
