# Generated by Django 3.0.8 on 2020-07-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_key',
            field=models.CharField(default=None, max_length=240, null=True),
        ),
    ]
